### PR TITLE
Update chef-ruby-lvm-attrib gem to 0.3.14

### PR DESCRIPTION
**Pull request by RoeeFabrikant**
# Description

Update chef-ruby-lvm-attrib gem to 0.3.14

## Issues Resolved

List any existing issues this PR resolves

## Check List

- [ ] A summary of changes made is included in the CHANGELOG under `## Unreleased`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable.

### CODE REVIEW

**Comment by damacus** [comment]
Can you add a changelog entry and I can get this shipped. Thanks!

**Comment by RoeeFabrikant** [comment]
> Can you add a changelog entry and I can get this shipped. Thanks!

Done :)
Thanks!

**Comment by RoeeFabrikant** [comment]
Hi @damacus 
Just wanted to send you a quick, friendly reminder on this :)

**Comment by kitchen-porter** [comment]
Released as: [6.1.17](https://github.com/sous-chefs/lvm/releases/tag/6.1.17)

**Pull request merged**
